{
 "title": "Frostless Network SMP",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Player",
    "label": "Player",
    "query": "SHOW TAG VALUES WITH KEY = \"player\""
   },
   {
    "name": "Entity",
    "label": "Entity",
    "query": "SHOW TAG VALUES WITH KEY = \"entity\""
   }
  ]
 },
 "panels": [
  {
   "title": "Animals bred by player",
   "type": "barchart",
   "gridPos": { "h": 18, "w": 9, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Animals" } },
   "targets": [
    {
     "alias": "$tag_player",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "player" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "animal_breed",
     "select": [
      [
       { "params": [ "entity_bred" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "entity", "operator": "=~", "value": "/^$Entity$/" },
      { "condition": "AND", "key": "player", "operator": "=~", "value": "/^$Player$/" }
     ]
    }
   ]
  },
  {
   "title": "Player",
   "type": "dalvany-image-panel",
   "gridPos": { "h": 8, "w": 4, "x": 10, "y": 0 },
   "targets": [
    {
     "alias": "$tag_player",
     "groupBy": [
      { "params": [ "player" ], "type": "tag" }
     ],
     "limit": "1",
     "measurement": "player_join",
     "select": [
      [
       { "params": [ "uuid" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "player", "operator": "=~", "value": "/^$Player$/" }
     ]
    }
   ]
  },
  {
   "title": "Foods Eaten",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_food",
     "groupBy": [
      { "params": [ "food" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "food_eaten",
     "select": [
      [
       { "params": [ "food_eaten" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "player", "operator": "=~", "value": "/^$Player$/" }
     ]
    }
   ]
  },
  {
   "title": "Animals Bred",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "($tag_entity) $tag_player",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "entity" ], "type": "tag" },
      { "params": [ "player" ], "type": "tag" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "animal_breed",
     "select": [
      [
       { "params": [ "entity_bred" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "player", "operator": "=~", "value": "/^$Player$/" },
      { "condition": "AND", "key": "entity", "operator": "=~", "value": "/^$Entity$/" }
     ]
    }
   ]
  },
  {
   "title": "Server Info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "Items crafted over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "alias": "$tag_item",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "item" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "player_craft",
     "select": [
      [
       { "params": [ "item_amount" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Mobs killed",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 23 },
   "targets": [
    {
     "alias": "$tag_entity",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "entity" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "monster_killed",
     "select": [
      [
       { "params": [ "entity_killed" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "player", "operator": "=~", "value": "/^$Player$/" }
     ]
    }
   ]
  }
 ]
}